### ISSUE TITLE
MXA links are broken

### ISSUE THREAD

**Issue by alsepkow** [microsoft/media-foundation#10]
Looks like the MXA MSDN page, MXA getting started guide, and stand alone download links have been taken down.

**Comment by edwpang** [comment]
Yeah, also MXA hyas been been updated for several years, and now it's totaly gone. It was pretty useful tool.

**Comment by alsepkow** [comment]
@edwpang We actually do still ship and update MXA. It's included in the ADK: https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install

With the installer you can select to only install MXA.
