### ISSUE TITLE
Samples throw exceptions on start

### ISSUE THREAD

**Issue by tuggernuts** [microsoft/media-foundation#15]
I just downloaded and built these 3 samples. The only one that executes is MediaEngineEMEUWP. The other 2 throw exceptions on debug start. Using VS 2019 16.8.3, with latest C++ redistributable.

I can provide stack traces if not reproducible.

I assume since one works, I have any necessary pre-req's installed.

**Comment by kumraj** [comment]
The media content link at line#18 in MediaEngineUWPSample/src/App.cpp is no longer available. Replace it with a working link or local content path and it should work fine.

**Comment by tuggernuts** [comment]
Yes, easy enough of a fix for both. Had assumed all 3 were looking at same url. Thanks.

**Comment by kumraj** [comment]
Issue resolved
