### ISSUE TITLE
MPEG-4 Media Source will not open files with bitrate greater than 4Gbps

### ISSUE THREAD

**Issue by AndrewRH** [microsoft/media-foundation#16]
Hi,

I hope I'm posting this in the right place.  Is this where some of the Media Foundation / Media dev team live? :)  I sure hope so, it's really hard to report issues in Media Foundation.

I've posted the details and files for this issue here:
https://stackoverflow.com/questions/63732879/how-to-get-microsoft-mpeg4-source-to-open-mov-with-bitrate-higher-than-4gbps

It seems to be a genuine bug in the MPEG-4 Source and it would be great to get it fixed.

Thanks,

**Comment by DavidS-msft** [comment]
We do. And we know of this current limitation. The main issue is that the Media Foundation property MF_MT_AVG_BITRATE is set at a 32-bit unsigned integer and because the bitrate is greater than a 32-bit integer it errors out.

**Comment by AndrewRH** [comment]
> We do. And we know of this current limitation. The main issue is that the Media Foundation property MF_MT_AVG_BITRATE is set at a 32-bit unsigned integer and because the bitrate is greater than a 32-bit integer it errors out.

Yes that's exactly what I suspected.  I guess in the future a new 64-bit bitrate attribute will be needed.  Perhaps for now it could be changed so that MPEG-4 Source sets MF_MT_AVG_BITRATE to 0xffffffff and still allows playback.  Then the new bitrate attribute could be queried to get the real bitrate when MF_MT_AVG_BITRATE  == 0xffffffff for anyone who really needs the exact value.

Thanks David 👍  your reply is much appreciated.  I spend a lot of time writing media software / MFT's etc in Windows (using MF and WinRT APIs) and I feel like there has been a bit of a MF dev-silence over the last few years (even the documentation hasn't been updated with many new API features missing documentation), so I really hope Microsoft is getting back to making some of the many internal API improvements more accessible to the dev community, gathering feedback etc.
