### ISSUE TITLE
MediaEngineDCompWin32Sample WM_SIZE issue

### ISSUE THREAD

**Issue by TerenceRussell** [microsoft/media-foundation#28]
Working with the latest VS2019 and SDK (as of today 2021-09-24), I'm finding that resizing the host window by pulling an edge causes the video area to snap to the 0,0 of the host window - thus overwriting the title bar.  

If I then move the window, the video snaps back to the client area of the host window.

![image](https://user-images.githubusercontent.com/11290019/134708403-ab9db4b6-fef1-4426-baed-8822a38cf266.png)

**Comment by cjrog** [comment]
It is possible that this is a result of a bug outside of MF that may have been fixed since this issue was filed. We would like to investigate more if you are still able to reproduce the problem. Please reopen this issue in that case.
