### ISSUE TITLE
MediaEngineEMEUWPSample doesn't display anything

### ISSUE THREAD

**Issue by jrmuizel** [microsoft/media-foundation#30]
I get an exception thrown in `MediaEngineExtension::BeginCreateObject` because the type is MF_OBJECT_BYTESTREAM and not MF_OBJECT_MEDIASOURCE. I'm not sure if the exception is expected or not. `MediaEngineExtension::BeginCreateObject` is called a second time with MF_OBJECT_MEDIASOURCE and succeeds that time.

**Comment by DavidS-msft** [comment]
That is expected. The Media Engine, for optimization, may attempt to first request a bytestream instead of a media source.

**Comment by jrmuizel** [comment]
@kumraj what was the change that fixed this?
