### ISSUE TITLE
Windows Media Player fails to play Opus audio track of AV1 files with MP4 container

### ISSUE THREAD

**Issue by vivienfr** [microsoft/media-foundation#36]
Windows Media Player in Windows 11 fails to play Opus audio track of AV1 files when MP4 container (ISO base media file format) is used.

The Opus audio track is played when the container is MKV (Matroska).

The standard plans to use AV1 with MKV and AV1 (This is the format used by YouTube) : https://en.wikipedia.org/wiki/AV1#Supported_container_formats

PC used: Windows Media Player 12.0 + Windows 11 21H2 with AV1 video extension installed. 

Sample MP4 video file: https://lafibre.info/videos/test/202008_fortnite_1984_24fps_1080p_av1.mp4
- Video track: AV1 1080p
- Audio track: Opus

**Comment by brbeec** [comment]
I confirmed that the Windows MP4 media source currently doesn't support Opus audio streams. I filed an internal work item to track this issue - we'll look into adding support for Opus in MP4 in a future release. Thanks for the feedback!

**Comment by vivienfr** [comment]
Would it be possible to request at the same time that the AV1 video extension is installed by default under Windows 11 ?

Microsoft Edge is one of the last browsers that does not support AV1 by default.

Support for AVIF images (A modern image format based on the AV1 video format) would also be appreciated: https://caniuse.com/avif

**Comment by vivienfr** [comment]
Would it be possible to request at the same time that the AV1 video extension is installed by default under Windows 11 ?

Microsoft Edge is one of the last browsers that does not support AV1 by default.

Support for AVIF images (A modern image format based on the AV1 video format) would also be appreciated: https://caniuse.com/avif

**Comment by brbeec** [comment]
The AV1 Video Extension is currently not preinstalled for Windows 11 due to legal/licensing concerns. Hopefully this situation will be resolved at some point in the future.

**Comment by megapro17** [comment]
> I confirmed that the Windows MP4 media source currently doesn't support Opus audio streams. I filed an internal work item to track this issue - we'll look into adding support for Opus in MP4 in a future release. Thanks for the feedback!

Your team is pathetic and useless . It doesn't do anything, doesn't fix such serious bugs. I left a report about this bug in feedback hub 5 years ago, not only was the bug not fixed, but my report just disappeared. MP4 specification does support Opus but nothing works in this stupid system. This bug affects any application that uses windows api for video playing

**Comment by regalialong** [comment]
Ugh, I hate to necro this but trying to stay respectful, WMF issues like this has seriously taken a few years off my life.

Having Opus work in the MP4 container would be very much appreciated as a generic alternative to AAC. And I'd personally like to see AV1 be shipped by default similar to VP9 for efficient video.

Is anybody over at MS still looking into the two? :)

**Comment by brbeec** [comment]
The [AV1 Video Extension](https://apps.microsoft.com/detail/9mvzqvxjbq9v) will come preinstalled with the vNext version of Windows 11.

Unfortunately supporting Opus in MP4 is still on the backlog (osgvsowi/40750000). Adding @kumraj and @DavidS-msft for visibility on this feature request.

**Comment by gamer191** [comment]
> The [AV1 Video Extension](https://apps.microsoft.com/detail/9mvzqvxjbq9v) will come preinstalled with the vNext version of Windows 11 (24H2).

Just wanted to clarify whether Windows 11 24H2 comes preinstalled with AV1? Also, what does vNext mean? Is it a typo for "next"?

If 24H2 does come with AV1, can you please update https://support.microsoft.com/en-au/windows/codecs-in-media-player-d5c2cdcd-83a2-4805-abb0-c6888138e456 (or pass feedback on to whoever can update it)

**Comment by megapro17** [comment]
> Also, what does vNext mean? Is it a typo for "next"?

No, it's a microsoft newspeak

> Unfortunately supporting Opus in MP4 is still on the backlog

Take your time, I know it's incredibly hard thing to do, to add support for an already supported codec that plays fine separately and in the mkv container. It should take another 5-10 years. You can't expect enthusiasts doing development in their spare time to fix bugs faster than a decade. It's not like it's a top 3 rich company in the world with their main product.

**Comment by brbeec** [comment]
> Just wanted to clarify whether Windows 11 24H2 comes preinstalled with AV1?

Yes, AV1 is preinstalled on Windows 11 24H2.

> Also, what does vNext mean? Is it a typo for "next"?

vNext = "next version". I just meant AV1 would be preinstalled in the next release of Windows, which was Windows 11 24H2.

> If 24H2 does come with AV1, can you please update https://support.microsoft.com/en-au/windows/codecs-in-media-player-d5c2cdcd-83a2-4805-abb0-c6888138e456 (or pass feedback on to whoever can update it)

I'm not sure how to update that documentation, but I'll try to find someone who does.

**Comment by jimm98y** [comment]
May I ask why is this issue closed when it's still reproducible in the latest Windows 11 26100.4652? I can play ".opus" as well as ".webm" with Opus audio track, yet after re-encoding the same .webm to ".mp4" the Media Player says it cannot play it because Opus is not supported. I understand that parsing the Opus ISOBMFF boxes is currently missing and needs to be implemented, I just wonder if this issue is still being tracked somewhere.

**Comment by brbeec** [comment]
> May I ask why is this issue closed when it's still reproducible in the latest Windows 11 26100.4652? I can play ".opus" as well as ".webm" with Opus audio track, yet after re-encoding the same .webm to ".mp4" the Media Player says it cannot play it because Opus is not supported. I understand that parsing the Opus ISOBMFF boxes is currently missing and needs to be implemented, I just wonder if this issue is still being tracked somewhere.

This issue is closed because the user who opened this issue closed it.

<img width="586" height="86" alt="Image" src="https://github.com/user-attachments/assets/c0394f7b-899e-4c1b-b688-df889281a04d" />

This feature request is tracked on our internal backlog (osgvsowi/40692886), but I can reopen this issue for public tracking.

**Comment by Anokino** [comment]
Any news on this ?

**Comment by brbeec** [comment]
> Any news on this ?

Yes! Adding Opus support to the MP4 media source was prioritized as part of the recent [Windows quality initiative](https://blogs.windows.com/windows-insider/2026/03/20/our-commitment-to-windows-quality/)! The work has been completed, and the feature is currently rolling out for Windows 11 24H2 and Windows 11 25H2 in [KB5089573 (OS Builds 26200.8524 and 26100.8524)](https://support.microsoft.com/en-us/topic/may-26-2026-kb5089573-os-builds-26200-8524-and-26100-8524-preview-f378c8ae-0170-47c9-a1e9-dfef978c8e17). It's under [Controlled Feature Rollout (CFR)](https://support.microsoft.com/en-us/windows/delivering-continuous-innovation-in-windows-11-b0aa0a27-ea9a-4365-9224-cb155e517f12), so it's initially only enabled for a fraction of the population. The ETA for 100% enablement is 6/23/26.

Support will also be coming to Windows 11 26H1 in an update later this month. I'll provide the build info and dates once they're available.

**Comment by megapro17** [comment]
No way, this bug didn't even 10 years old
Vivetool id btw?

**Comment by brbeec** [comment]
Here's the current status of the rollout of Opus support in MP4:
- Windows 11 24H2 and Windows 11 25H2: [KB5089573 (OS Builds 26200.8524 and 26100.8524)](https://support.microsoft.com/en-us/topic/may-26-2026-kb5089573-os-builds-26200-8524-and-26100-8524-preview-f378c8ae-0170-47c9-a1e9-dfef978c8e17)
  -  Controlled Feature Rollout (CFR) status: 100% enabled as of 6/24/26
- Windows 11 26H1: [KB5095091 (OS Build 28000.2340)](https://support.microsoft.com/en-us/topic/june-23-2026-kb5095091-os-build-28000-2340-preview-255237ff-1236-4ad7-a087-251eb0cf8869)
  - Controlled Feature Rollout (CFR) status: 0% enabled
  - The ETA for 100% enablement is 7/21/26

**Comment by brbeec** [comment]
The rollout of Opus support in MP4 is complete.
- Windows 11 24H2 and Windows 11 25H2: [KB5089573 (OS Builds 26200.8524 and 26100.8524)](https://support.microsoft.com/en-us/topic/may-26-2026-kb5089573-os-builds-26200-8524-and-26100-8524-preview-f378c8ae-0170-47c9-a1e9-dfef978c8e17)
  -  Controlled Feature Rollout (CFR) status: 100% enabled as of 6/24/26
- Windows 11 26H1: [KB5095091 (OS Build 28000.2340)](https://support.microsoft.com/en-us/topic/june-23-2026-kb5095091-os-build-28000-2340-preview-255237ff-1236-4ad7-a087-251eb0cf8869)
  - Controlled Feature Rollout (CFR) status: 100% enabled as of 7/21/26

**Comment by frfeed123** [comment]
so basically someone who prefers 23h2 like me is out of luck?

**Comment by brbeec** [comment]
> so basically someone who prefers 23h2 like me is out of luck?

Windows 11 23H2 Home/Pro reached the end of updates 9 months ago: [Windows 11, version 23H2 reaching end of updates (Home, Pro) - Microsoft Lifecycle | Microsoft Learn](https://learn.microsoft.com/en-us/lifecycle/announcements/windows-11-23h2-end-of-updates-home-pro).

Support for Opus in MP4 has been added to all of the Windows 11 Home/Pro releases that are still supported (24H2, 25H2, and 26H1): [Windows 11 Home and Pro - Microsoft Lifecycle | Microsoft Learn](https://learn.microsoft.com/en-us/lifecycle/products/windows-11-home-and-pro).

So yes, you'll need to update to Windows 11 Home/Pro 24H2 or higher if you want this feature.
