### ISSUE TITLE
HEVCVideoExtension support Windows Server (2019 / 2022)

### ISSUE THREAD

**Issue by persskog** [microsoft/media-foundation#52]
Is it possible to install the _HEVCVideoExtension_ on a Windows Server (2019 / 2022) ?

Need to do some video processing with the IMFSourceReader (server-side).

**Comment by cjrog** [comment]
We only support Server installation of HEVC via Volume Licensing Service Center. ([https://www.microsoft.com/licensing/servicecenter/])

**Comment by cjrog** [comment]
It is available as a package on the VLSC site linked in the above message. We do not have specific instructions on how to access it from the site, but that is where you would find it.
